version: "3.2"

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: ${APP_NAME:?err}-php
    volumes:
      - .:/var/www/html/:cached
    environment:
#      XDEBUG_CONFIG: "remote_host=192.168.1.40 remote_enable=1 remote_autostart=off remote_port=9000"
      PHP_IDE_CONFIG: "serverName=Docker"

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME:?err}-nginx
    ports:
      - ${NGINX_OUTSIDE_PORT}:80
    links:
      - 'php'
    volumes:
      - .:/var/www/html/
      - ./docker/nginx:/etc/nginx/conf.d

  mariadb:
    image: mariadb:10.3.9
    container_name: ${APP_NAME:?err}-mariadb
    restart: 'on-failure'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_OUTSIDE_PORT}:3306
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    external: true
